Fix TypeError originated by missing paramater
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    clothing.withdraw(25.55)
TypeError: withdraw() missing 1 required positional argument: 'description'

Missing default intialization sor parmater description in deposit method.