Convert asterix_per_side variable to correct format in budget.py
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    print(food)
  File "/media/ricardo/FE242A58242A13E5/Users/LapTop/Desktop/Python_For_Everybody/Budget-App/budget.py", line 40, in __str__
    line1 = asterix_per_side*'*' + self.name + asterix_per_side*'*'
TypeError: can't multiply sequence by non-int of type 'float'

Edit lines 39 and 42, asterix_per_side is converted to tyoe int