Fix AssertionError
Add 'balls_drawn' variable instead of use 'contents2' attribute from 'temp' object

Thanks to https://github.com/adviksinghania/probability-calculator/blob/main/prob_calculator.py

======================================================================
FAIL: test_prob_experiment (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ricardo/FE242A58242A13E5/Users/LapTop/Desktop/Python_For_Everybody/Probability-Calculator/test_module.py", line 32, in test_prob_experiment
    self.assertAlmostEqual(actual, expected, delta = 0.01, msg = 'Expected experiment method to return a different probability.')
AssertionError: 0.0 != 1.0 within 0.01 delta (1.0 difference) : Expected experiment method to return a different probability.

----------------------------------------------------------------------
Ran 3 tests in 1.497s